# File              : .drone.yml
# Author            : Milton Carlos Katoo <mckatoo@gmail.com>
# Date              : 25.06.2020
# Last Modified Date: 26.06.2020
# Last Modified By  : Milton Carlos Katoo <mckatoo@gmail.com>
kind: pipeline
type: docker
name: default

steps:
- name: frontend
  image: node:13.14.0
  environment:
  depends_on:
  - backend
  - sql
  - database
  commands:
  - sleep 30
  - npm i
  - npm run test

- name: sql
  image: postgres
  depends_on:
  - database
  commands:
  - sleep 10
  - psql -U postgres -d test -h database -a -f database/database.sql

services:
- name: database
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: test
    POSTGRES_HOST_AUTH_METHOD: trust

- name: backend
  image: node:12.18.0
  environment:
    DATABASE_URL: "postgresql://postgres:@database:5432/test?schema=public"
  depends_on:
  - sql
  - database
  commands:
  - git clone https://github.com/mckatoo/formataja api
  - cd api
  - npm i
  - npm run build
  - sleep 20
  - npm run start
